#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

composer run lint:fix
composer run lint:dry
exitCode="$?"
echo $exitCode
if [ $exitCode != 0 ]; then
    echo "husky - $hook_name hook exited with code $exitCode (error)"
    exit $exitCode
fi
exit 0
